### ISSUE TITLE
List Index out of Range when specifying Z

### ISSUE THREAD

**Issue by spaulaus** [kmiernik/Chart-of-nuclides-drawer#2]
When running the program with the following command: 

    ./ChartDrawer.py --halflives --z 15 25 nubase12.xml test.svg

I get the following error:

    Traceback (most recent call last):
      File "./ChartDrawer.py", line 600, in <module>
        draw_numbers(layers, shape, n_limits, z_limits, size)
      File "./ChartDrawer.py", line 465, in draw_numbers
        while ( not(shape[n][z_first]) and 
    IndexError: list index out of range

However, if I use a different region (e.x. --z 8 28) the program runs as expected.

**Comment by kmiernik** [comment]
I cannot reproduce this error. Perhaps with the fixed nubase12.xml it is gone? Can you check that?

**Comment by spaulaus** [comment]
The issue has been resolved with the resolution of Issue #3.
