### ISSUE TITLE
Missing Isotopes

### ISSUE THREAD

**Issue by spaulaus** [kmiernik/Chart-of-nuclides-drawer#3]
I generated the attached image with the command:

    ./ChartDrawer.py nubase12.xml full.svg

There seem to be a number of missing isotopes (24Ne, 40P) along with some missing ones on the neutron dripline (28,30F, 33Ne, etc.). 

![missingisotopes](https://cloud.githubusercontent.com/assets/1553042/10416995/dc04c346-6ffa-11e5-842b-894e397bb5e9.png)

**Comment by gchristian321** [comment]
I've run into this too. It looks to be a problem with the nubase12.xml file. The nubase03.xml file seems to work okay, so as a quick solution you can just draw your chart using that instead.

**Comment by kmiernik** [comment]
Thanks for your comments. I hope I fixed most of the issues. The original ascii file I have from Nubase is illformed in many places, they use inconsistent symbols, formatting etc. Some isomers are still missing in the fixed nubase12.xml, but at least the map should be better now.
